### ISSUE TITLE
Wrong formatting code in chat

### ISSUE THREAD

**Issue by NaksTur** [msifd/misca#1]
Когда игрок пишет сообщение в чат, ТаббиЧат делит его на две и больше частей, отправляя большое сообщение "по частям". Первое сообщение проходит нормально, второе и каждое последующее ванильного белого цвета.

![image](https://user-images.githubusercontent.com/22483969/28586574-f5698b52-717c-11e7-8d7a-af9931db01f1.png)

**Comment by msifd** [comment]
Добрый день и спасибо, что пользуетесь нашим модом! Следует отметить, что если ТаббиЧат дели на несколько частей, то они не отправляются вовсе! Баг на скриншоте скорее всего по другой причине поэтому данный вопрос закрывается.

**Comment by NaksTur** [comment]
Да всмысле по другой

**Comment by msifd** [comment]
Ванильный майнкрафт тоже переносит длинные сообщения, но не разделяет их и имеет отграничение.

**Comment by NaksTur** [comment]
Возможно тогда дело в том, что там на вторую строку мод не переносит форматтинг код?

**Comment by msifd** [comment]
Да, именно в этом. Надо это пофиксить.
