### ISSUE TITLE
Команда инкогнито

### ISSUE THREAD

**Issue by NaksTur** [msifd/misca#3]
По вводу команды /incognito делать ник над башкой невидимым, а в чате вместо имени выводить ?????.

По вводу команды /publicmode делать ник над башкой видимым на 300 блоков, желательно - чтобы он не затемнялся стенами. 

По вводу команды  /changeling %имяперсонажа% (отсылка к тому, что ты делал для Поняча) делать табличку над головой под имя персонажа и ник в чате, как у него. Скин можно не менять (не ебись, это базовая фича МПМ)

**Comment by msifd** [comment]
В 5dd4adb94089b46cfb1eebbeeebe5c0bb2870db5 добавил /incognito. Остальные не будут работать на каульдроне.
